- src/plugin/patchmanager.json
The commit only changes "patchmanager" to "Patchmanager" in order to have the entry capitalized in the jolla-settings app. (All entries are with capital letter, i found it ugly to have patchmanager entry starting with lowercase").
> Capitalize patchmanager entry on the jolla-settings menu

- .github/workflows/build.yml
- rpm/patchmanager.spec
- src/preload/preload.pro
This adds the correct lib64 location for the preloaded so.
Also, because a previous version of this might have been installed from b100dian OBS or chum, which used the 64-bit binary in /lib/, that needs to be cleared from ld.so.preload.
<details>
<summary>Old description</summary>
Without bash installed, the busybox shell was erroring out with "Substitution failure".
This changes the script to no longer need `${PIPESTATUS[0]}` which is the cause of the above failure.
Also, when building for aarch64, there is some mismatch between where a lib is packaged and where is looked up. The 'fix' is to currently just hardcode "lib" - that's why I say its' the naive fix, only to unblock building/running.
</details>
> Add aarch64 support

- src/qml/PatchManagerPage.qml
"Unapply All" menu option is destructive - add a remorse timer to it to avoid "fat-fingering"
See Issue #20
https://github.com/sailfishos-patches/patchmanager/issues/20
> [ui] add Remorse Popup to Unapply All menu action

- rpm/patchmanager.spec
- src/etc/etc.pro
- src/etc/whitelist-common-patchmanager.local
- src/src.pro
See Issue #55 for discussion.
Installs a new file `whitelist-common-patchmanager.local`, and adds an include line to `/etc/firejail/whitelist-common.local`.
Tested on 4.0/Xperia10-DS and 4.2/GeminiPDA, works.
> [firejail] add and install our own whitelist

- rpm/patchmanager.spec
Increase version number & add dep to SFOS >= 3.4.0
- Increase version number from 3.0.1 to 3.1.0
- Add runtime dependency to SailfishOS >= 3.4.0, because I always hated that Patchmanager was installable on old SailfishOS releases, which it does not support any more.
> Increase version number & add dep to SFOS >= 3.4.0

- .gitignore
- src/qml/PatchManagerPage.qml
- src/qml/patchmanager.cpp
- src/qml/patchmanager.h
Navigating to a non-existing page does not throw anymore - test existence first.
Cherry-picking @elros34's https://github.com/elros34/patchmanager/commit/54cf701439bf41b2d4d9ebaff1389ff9f62fa84d in spirit + authorship
> Fix pageStack.push doesn't throw exception when file is missing. Fixes #54

- src/tools/pm_apply
- src/tools/pm_unapply
... plus a single superfluous quoting of a fixed string for consistency between pm_apply and pm_unapply
> [pm_apply / pm_unapply] Add missing quoting

- src/qml/PatchManagerPage.qml
- src/qml/settings-patchmanager.ts
Add a (Unicode) warning character to patch names if they might conflict with others.
Also fixes spelling of the corresponding warning.
> Show warning label for conflicting patches

- src/qml/WebCatalogPage.qml
- src/qml/webpatchesmodel.cpp
- src/qml/webpatchesmodel.h
Sort patches by localized category and displayed name. The "other" category is always displayed at the end of the list.
> Sort web patches by category and name

- src/qml/WebPatchPage.qml
- src/qml/patchmanager.cpp
- src/qml/patchmanager.h
See issue #33
https://github.com/sailfishos-patches/patchmanager/issues/33
Concept ported from @elros, ac0991b
https://github.com/elros34/patchmanager/commit/ac0991b1b27df010066fa4e3f8f287c6b1004a3e
> Do not call ssu to determine OS Version

- src/bin/patchmanager-daemon/dbus/org.SfietKonstantin.patchmanager.xml
- src/bin/patchmanager-daemon/patchmanagerobject.cpp
- src/bin/patchmanager-daemon/patchmanagerobject.h
Should fix some fallout from PR #65, which removed Ssu calls from patchmanager, but left pachmanagerobject still using ssu values. 
This led to the compatibility checks on web catalog patch pages failing (all versions displayed as incompatible).
> Fix PR 64: Move from SsuRelease to OsRelease

- patchmanager.pro
- translations/settings-patchmanager-de.ts
- translations/settings-patchmanager-en.ts
- translations/settings-patchmanager-es.ts
- translations/settings-patchmanager-fi.ts
- translations/settings-patchmanager-fi_FI.ts
- translations/settings-patchmanager-fr_FR.ts
- translations/settings-patchmanager-hu.ts
- translations/settings-patchmanager-nl.ts
- translations/settings-patchmanager-nl_BE.ts
- translations/settings-patchmanager-pl.ts
- translations/settings-patchmanager-pt_BR.ts
- translations/settings-patchmanager-ru.ts
- translations/settings-patchmanager-sl.ts
- translations/settings-patchmanager-sl_SI.ts
- translations/settings-patchmanager-sv.ts
- translations/settings-patchmanager-zh_CN.ts
- translations/settings-patchmanager.ts
This should trigger transifex.
Also there were some strings marked as "vanished" in https://github.com/sailfishos-patches/patchmanager/pull/53 - My guess is Qt Creator building (I built from commandline). I reverted only the translations/ part of that commit, added back what my commandline build generated, then added the de strings.
Next let's sett if transifex gets updated (it did, on my [super secret org](https://www.transifex.com/b100dian/patchmanager3-1/translate/#de/translations-settings-patchmanager-ts--master/334886395?q=text%3Aother))
> Update translations/settings-patchmanager.ts file on master should trigger transifex

- src/bin/patchmanager-daemon/patchmanagerobject.cpp
I noticed during dogfooding that downloading packages from Web Catalog which have .zip packages would not work.
The download would complete successfully, but then the patchmanager daemon would start unzipping, and the unzip child process would hang indefinitely (apparently waiting for input on fd 0).  
This then causes the patchmanager daemon to hang while it waits.
Suspecting this might have to do with zip packages being placed in `/tmp`, I moved that location within `/tmp/patchmanager3/work`, and changed the call to unzip to force-overwrite files in the target dir. This makes unzipping work again, although I'm not exactly sure why.
This PR also includes two other enhancements:
- make all paths to external binaries static constants on the top of the source file
- support more than just …
> Fix zip package handling, enhance decompression capabilities

- translations/settings-patchmanager.ts
... which just adds Capitalization
As we don't have a dedicated -en translation file any more because of
PR #108 , and we can't change the strings directly in the source, as
- that would likely make the web catalog not work any more
- would require changing of the .json specification
- ^^^ would require patch authors to change all .json files
- would require changing of the web catalog web backend
... this adds translations for strings used in the cpp source
> Translate Category names in ENglish

- patchmanager.pro
Follow-up to PR #153 
Up until now there was no .qm file installed for English (only existing -XX.ts files were considered by the build process).
In order to have translations show up we generate and install an -en.qm file, using the translation source as source.
> Generate -en.qm file from translation source

- src/bin/patchmanager-daemon/patchmanagerobject.cpp
- src/bin/patchmanager-daemon/patchmanagerobject.h
- src/qml/SettingsPage.qml
- src/qml/patchmanager.cpp
- src/qml/patchmanager.h
When applying a lot of patches the notification popups get in the way, and clutter the Notification view.
This allows the user to turn off success notifications for applying patches.
> [ui] Add option to suppress notifications

- src/tools/pm_apply
Use absolute paths for testing *and* sourcing.
> [pm_apply] Fix manglelist path

- src/tools/pm_apply
This still ought be functionally equivalent to the original version as of PM 3.2.0: please test!
> Prepare for multiple conversion runs

- rpm/patchmanager.spec
See https://forum.sailfishos.org/t/announcing-sailfishos-chum-gui-0-3/9839/29 and https://github.com/sailfishos-chum/main/blob/main/Metadata.md for the chum metadata information.
> Spec: modify description, add chum metadata

- src/tools/pm_apply
corrects regular expressions:
1. '+' has special meaning, escape it
2. handle patches with "git-style" prefixes in the diff header, see [Test Cases #232 (comment)](https://github.com/sailfishos-patches/patchmanager/discussions/232#discussioncomment-1966155)
> pm_apply: improve regexp

- src/tools/pm_apply
This enhances PR #238, while retaining its intention.
> (Re-)move misplaced log output and counter initialisation

- src/tools/pm_unapply
`if [ -f "$PATCH_FILE" ]` and later `if [ ! -f "$PATCH_FILE" ]` was a bit mindless.
> [pm_unapply] Enhance checks&balances and debug output

- src/tools/pm_apply
Re-do commit b1fea73 (as 9e16ec6) and a fixed version of commit 2a1f08b (as dd1a211) …
> [pm_apply] Do convert multiple libpath references

- rpm/patchmanager-rpmlintrc
- rpm/patchmanager.spec
- src/bin/patchmanager-daemon/patchmanager-daemon.pro
Aims to remove some common complaints from rpmlint.
NOT sure if compiling PIC/PIE is smart for the daemon, but I have tested running it that way, seems to work.
> Fix some complaints from rpmlint

- src/tools/pm_apply
See also #220.
This moves the sed call outside of the detection/mangle list loop.
sed command is built in the loop, but only one call to sed is made.
This saves a couple of greps and tests as well.
Tested against Test Case 2-2, from https://github.com/sailfishos-patches/patchmanager/commit/9fb6adb67a4a0948eeb731c08fc2dfa17a88f6c3#diff-bdc16c81678138d1bc10b9ac315b66564aaf85cad91efaed15e375ef837fd7a3
> [pm_apply] improve mangling by patching outside the loop

- src/tools/pm_apply
* Do not quote "+" in BREs, because BREs are the default for grep and sed (see their man-pages) and in BREs the "+" character has no special meaning, plus https://www.gnu.org/software/sed/manual/sed.html#BRE-vs-ERE
* Replace all occurrences of each path pattern with its replacement pattern, instead of only the first occurrence of each path pattern.
> pm_apply: Do not quote "+" for BREs

- src/bin/dialog/dialog.qml
- src/bin/patchmanager-daemon/patchmanagerobject.cpp
- src/qml/SettingsPage.qml
- src/qml/patchmanager.cpp
- translations/settings-patchmanager.ts
…, see https://github.com/sailfishos-patches/patchmanager/wiki/Terms-and-wording#0---9
And check all and adapt all but one line numbers in translations/settings-patchmanager.ts, including …
fix quite some line number references being broken for long.
> l18n: Adapt to bitness nomenclature and fix all line number references

- rpm/patchmanager.spec
… and use the unified wording, as of https://github.com/sailfishos-patches/patchmanager/wiki/Terms-and-wording#sailfishos
> Spec file: Slightly enhance description

- src/qml/PatchManagerPage.qml
… "Settings" shall be below "About" and easier to reach, plus "Deactivate all Patches" the hardest to reach (i.e., topmost)
> PatchmanagerPage: Reorder pulley menu entries

- rpm/patchmanager.spec
… to prepare a new, fixed release of v3.2.1 (see [SailfishOS:Chum GUI application issue 111](/https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/111), plus move the comments for the SailfishOS:Chum metadata closer to it.
> Spec file: Increase version number

- src/bin/patchmanager-daemon/patchmanagerobject.cpp
> Fix no-notification logic

- src/qml/DevelopersPage.qml
… because AUSMT is not used by Patchmanager any more for long (since v3-alpha).
> DeveloperPage: Remove AUSMT entry

- rpm/patchmanager.spec
- Introduce `%defattr(-,root,root,-)` in `%files` section
- Alter package name: `test-cases`→`testcases`, because it becomes prefixed with `%{name}-` to `patchmanager-testcases` (avoiding two hyphens).
- Obey [SailfishOS:Chum PR 70](https://github.com/sailfishos-chum/main/pull/70)
- Overhaul descriptions: `Summary:`, `%description` and "Chum metadata"
- Generically applied `%{url}` at many places and `%{name}` at a few additional ones.
- [Clean up `%files testcase` section](https://github.com/sailfishos-patches/patchmanager/pull/289/commits/a41e9a985b8874da7334135a0bb8f22fd6becb06) conforming to [classic, authoritative reference](http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html#S3-RPM-INSIDE-DIR-DIRECTIVE)s.
> spec file: quality assurance for test-cases

- rpm/patchmanager.spec
… `testcases`, because they do depend on Patchmanager to run.
> spec file: Add `Requires: %{name}` to subpackage

- rpm/patchmanager.spec
… because they are translated into empty lines, which shows when viewing packages from SailfishOS:Chum with the `rpm` utility.
> spec file: Pull comments out of %description sections

- src/qml/WebPatchPage.qml
This relaxes/enhances the "can it be installed" checks in the Web Catalog Patch page so installed patches can be installed again.
Use case: lazy patch developers like myself don't bump the patch version when updating OS Compatibility. This results in (old) installed patches shown in red in the main patch list.  
Having the possibility to re-install updates the metadata (at the least), making the red 'incompatible' color go away.
... and a bit of trojan horse commit: highlight the compatible OS version in the "compatible" list.
> Allow re-installation of installed patches from Web Catalog page

- README.md
… point out that an archive file has to be uploaded to the Web Catalog.
> [README] Unify spelling (use BE etc.) and

- rpm/patchmanager.spec
- `%global` instead of `%define` for static expressions: `%global`s are evaluated once when set, `%define`s are evaluated each time used.  Plus the scope of `%global`s is all sections, including the scriptlets.
- `-n %{name}-%{version}` always has been the default for `%setup`, hence omitted now.
-  `rm -rf %{buildroot}` as first statement in the `%install` section is long obsolete, thus superfluous.
> Use modern statements in spec file

- patchmanager.pro
- src/bin/dialog/dialog.pro
- src/bin/patchmanager-daemon/patchmanager-daemon.pro
- src/preload/preload.pro
- src/qml/qml.pro
Since warnings seem to be gone, let's keep it this way.
(I converted a file with dos2unix, so you might need to append `?w=1` to the diff url)
> Treat warnings as errors

- src/qml/PatchManagerPage.qml
- src/qml/SettingsPage.qml
- src/qml/WebPatchPage.qml
- src/qml/patchmanager.cpp
- src/qml/patchmanager.h
- src/qml/plugin.cpp
> Split "Allow incompatible Patches" from "Developer Mode"

- src/qml/WebPatchPage.qml
Add a pulley menu to the Patch page of a Web Catalog entry.
Allows developers to quickly access the Web Catalog, i.e. to change some information on the given patch.
Toggled by developer mode.
> Developer Mode: allow to jump to Patch Project page

- src/bin/patchmanager-daemon/patchmanagerobject.cpp
Not sure in which SFOS release `systemctl-user` moved from `/bin/` to `/usr/bin`, but on 4.4.0.72 that's where it lives.
Do we need to take care about this location in any of the older supported versions?
Also removes the double execution of it which I don't think was on purpose.
> fix systemctl location

- rpm/patchmanager.spec
To prepare for a possible move of the Web Catalog infrastructure, make the core variables configurable/defined in the .spec file
> [web catalog  migration] define compile-time variables in .spec

- src/qml/SettingsPage.qml
… as already the case for all other strings, e.g., "Enable …" etc.
> [String] Always use simple present tense

- rpm/patchmanager.spec
… to calm down some versions / configurations of `rpmlint`: Missing `%changelog` section or file is punished with an error, an inconsistent version number only with a warning.
- Update homepages to OpenRepos pages (looks more representative)
- Post release version increase
> [spec file] Insert dummy changelog with a correct entry 

- rpm/patchmanager.spec
Never saw a reference, so document it now.
> Add comment WRT values for the Group field

- rpm/patchmanager.spec
It looks like 3.2.8 was missed in the spec file!
Rather than reissuing a correct 3.2.8 release, proceed to 3.2.9.
Luckily it looks like this mishap was automagically alleviated by the SailfishOS-OBS, which rewrote the version tag to 3.2.8 (likely based on the git tag)!
> Pre release version increase

- rpm/patchmanager.spec
- src/qml/patchmanager.cpp
- src/qml/patchmanager.h
This was introduced by https://github.com/sailfishos-patches/patchmanager/commit/e30292be22fc6644e8b5ba32ac9612395bb11aff#diff-df38830cae3d3051528c63a2740fe3b0b4ec2c6b59aadab35dce5a1b6e995dd4R1016-R1035.  I still do not understand the purpose of this addition, specifically in the light of the comment(s) stating *"probably dead code, need to investigate"*: It sure is dead code, as these two newly added classes here do not contain any code at all.  Likely this is a combination of my lack of understanding and these comments lacking information needed for me to understand the purpose of this addition.
Another point to investigate: Why did [earlier CI runs not show this compile failure](https://github.com/sailfishos-patches/patchmanager/actions)?
> [patchmanager.cpp] Fix-up release 3.2.10 ⇒ 3.2.11

- .github/workflows/ci-on-pull_req.yml
- .github/workflows/ci-on-tags.yml
Trigger / Rationale: Trying to download three multi-GB, layered docker images in a single job may result in `docker: write /var/lib/docker/tmp/GetImageBlobXYZ: no space left on device.`, see https://github.com/sailfishos-patches/patchmanager/actions/runs/5871696093/job/15921691170#step:7:45
Hence splitting the "big" `CI on tags` workflow into two jobs and slightly enhancing both CI workflows.
> Slightly overhaul CI workflows

- .github/workflows/ci-on-tags.yml
For details see new comment in the altered file.
> [ci-on-tags.yml] Redefine LATEST sensibly

- .github/workflows/ci-on-pull_req.yml
- .github/workflows/ci-on-tags.yml
- .github/workflows/gendoc-create-html_qt56.yml
* **`ci-on-tags.yml`** & **`ci-on-pull_req.yml`**
- [`ubuntu-22.04` **→** `ubuntu-24.04`](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
- [`actions/checkout@v3`**→**`@v4`](https://github.com/actions/checkout#readme)
- [`actions/upload-artifact@v3`**→**`@v4`](https://github.com/actions/upload-artifact#readme)
* **`gendoc-create-html_qt56.yml`**
- [`ubuntu-22.04` **→** `ubuntu-24.04`](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
- [`actions/checkout@v3`**→**`@v4`](https://github.com/actions/checkout#readme)
- …
> [.github/workflows/*] Update GH-actions' and Linux versions

- .github/workflows/ci-on-tags.yml
For details, see https://github.com/sailfishos-patches/patchmanager/pull/479#pullrequestreview-2483451820.
Extends PR #472.
> [ci-on-tags.yml] Also build with SDK for 4.6.0

- .github/workflows/ci-on-tags.yml
This construct was working fine for years in GH actions YML files, but ceased to some time between mid-Februray and mid-March 2025.
```
jobs:
<job name>:
env:
RELEASE: ${{ env.LATEST }}
```
And "Yes, the variable [`env.LATEST` was correctly set](https://github.com/sailfishos-patches/patchmanager/pull/496/files#diff-67b09c17f87da4adcefdd2a8cad10e771ed3b562773c7134e46d53be4ac1f5faL13-L17)"!
The [resulting error message](https://github.com/user-attachments/assets/0159786c-1d7d-4f5e-9af8-57fb58498151) is:
>  Check failure on line 40 in .github/workflows/ci-on-tags.yml
GitHub Actions / CI on tags
> Invalid workflow file
> The workflow is not valid. .github/workflows/ci-on-tags.yml (Line: 40, Col: 16): Unrecognized named-value: 'env'. Located at position 1 within expression: env.LATEST
> [ci-on-tags.yml] Fix new sematic error in old code

- src/qml/AboutPage.qml
- src/qml/PatchManagerPage.qml
- src/qml/UnifiedPatchPage.qml
- src/qml/WebPatchPage.qml
- translations/settings-patchmanager.ts
I have made changes according to the earlier discussion, see it here: https://github.com/sailfishos-patches/patchmanager/discussions/157#discussioncomment-12111731
Summarum:
1. "Patch details" -> "Details"
2. "Openrepos" -> "OpenRepos"
3. "Sources" -> "Source code"
4. "May conflict with:" -> "May conflict with the following Patches:"
> Minor adjustments to a couple of text strings
