- rpm/patchmanager.spec
- rpm/patchmanager.yaml
- src/bin/patchmanager-daemon/dbus/org.SfietKonstantin.patchmanager.xml
- src/bin/patchmanager-daemon/patch/patch.json
- src/bin/patchmanager-daemon/patch/unified_diff.patch
- src/bin/patchmanager-daemon/patchmanager-daemon.pro
- src/bin/patchmanager-daemon/patchmanagerobject.cpp
- src/bin/patchmanager-daemon/patchmanagerobject.h
> Added unapplyall patch and dbus method to daemon

- src/qml/SettingsPage.qml
- src/qml/settings-patchmanager.ts
- translations/settings-patchmanager-de.ts
- translations/settings-patchmanager-en.ts
see Issue #25
https://github.com/sailfishos-patches/patchmanager/issues/25
> [ui] add descriptions in settings, rename developer mode

- src/bin/patchmanager-daemon/check-package.sh
... and omit a few superfluous curly braces, plus unify the syntax used for variable substitutions.
> [check-package.sh] Add proper quoting

- src/qml/AboutPage.qml
- src/qml/plugin.cpp
NOTE: license given is BSD-3 for now, clarification still open about that, see in PR #61
Fixes #12
https://github.com/sailfishos-patches/patchmanager/issues/12
> Redesign About page, add License and Source links

- LICENSE
- rpm/patchmanager.spec
... as most files already carry this license, no file carries any other license, only a few shell scripts did not mention a license.  Now also added to the spec file and the project root directory.
> Add BSD-3-clause license

- translations/pull.sh
See https://www.transifex.com/coderus/patchmanager3/languages/
> Adapt to current set of (top-level) laguages

- translations/settings-patchmanager.ts
As so often: Fatfingering happens with the simple, easy things.
> Fix settings-patchmanager.ts

- src/qml/WebCatalogPage.qml
Fixes: #152
https://github.com/sailfishos-patches/patchmanager/issues/152
> Web Catalog Page: translate category also in regular view

- rpm/patchmanager.spec
Original title:
Change sed delimiter character from # to @
... because it irritates the syntax highlighter (and me, every time I read it).
> Remove qmlplugindump call from spec file

- src/qml/PatchManagerPage.qml
- src/qml/WebPatchPage.qml
- translations/settings-patchmanager.ts
Discussed at https://github.com/sailfishos-patches/patchmanager/pull/155#issuecomment-961252475
> "Patch info" -> "Patch details"

- rpm/patchmanager.spec
For details, see https://github.com/sailfishos-patches/patchmanager/discussions/113
> Increase version to 3.1.1

- src/qml/UnifiedPatchPage.qml
feel free to push small things to this
> Trivial fixes for various UI complaints

- src/tools/pm_apply
> [pm_apply] Fix case of empty MANGLE_CANDIDATES

- doc/example_legacy_patch.json.md
… at https://github.com/sailfishos-patches/patchmanager/wiki/Terms-and-wording
> Update wording to the consolidated nomenclature

- README.md
See https://github.com/sailfishos-patches/patchmanager/wiki/Terms-and-wording
> [README.md] Update wording to the consolidated nomenclature

- translations/settings-patchmanager.ts
> settings-patchmanager.ts: Fix broken XML tag

- README.md
… add section covering SailfishOS:Chum.
> README: Sync intro with spec file / OpenRepos, plus

- translations/settings-patchmanager.ts
Results from:
-  `git checkout 3.2.4`
-  `lupdate *pro -ts translations/settings-patchmanager.ts`
-  `restore translations/settings-patchmanager-*ts`
- `git diff  > translations-3.2.4.diff`
-  `git switch master`
- `git apply  translations-3.2.4.diff`
- `git commit`
-  `lupdate *pro -ts translations/settings-patchmanager.ts`
-  `restore translations/settings-patchmanager-*ts`
- `git commit`
Should fix #357.
> Update translation strings

- translations/settings-patchmanager.ts
I should have pushed this to the feature branch for #372 before merging.
Oh well, too late.
> Update translation string for #372

- src/qml/WebPatchPage.qml
- translations/settings-patchmanager.ts
"click"→"tap" in the source code file and also in the source strings TS file to avoid a `lupdate` / `lrelease` run.
> "click" → "tap"

- .github/workflows/ci-on-pull_req.yml
- .github/workflows/ci-on-tags.yml
… plus: Run Docker not privileged, see https://docs.docker.com/engine/reference/commandline/stop/
> Beautify CI output & sh_mb2 script

- rpm/patchmanager.spec
… see https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/149#issuecomment-1427147040
Missed in commit 0085583 for PR #417.
> Use `%if 0%{?_chum}` to enable SailfishOS:Chum metadata conditionally, … 

- .github/workflows/gendoc-create-html_qt56.yml
Reference: https://github.com/sailfishos-patches/patchmanager/pull/449#issuecomment-1681156014
> [gendoc-create-html_qt56.yml] Omit check to "fix" explicitly empty input

- .github/workflows/ci-on-pull_req.yml
- .github/workflows/ci-on-tags.yml
- .github/workflows/gendoc-create-html_qt56.yml
YAML does not allow for a comment in the same line as a statement.
> [Workflows] Fix YAML syntax

- src/qml/RestartServicesDialog.qml
See [line 95](https://github.com/sailfishos-patches/patchmanager/pull/463/files#diff-afc5c5bd5b81cf0d933a1714b2b351ee6f521f116ebec886d5bfb5e8fdc03d20R95) and https://github.com/sailfishos-patches/patchmanager/pull/459/files/f38f25bdc1c9ece8004051fb557d751c212d38db#diff-afc5c5bd5b81cf0d933a1714b2b351ee6f521f116ebec886d5bfb5e8fdc03d20R100
> [src/qml/RestartServicesDialog.qml] Remove line duplicated by PR #459

- .github/workflows/ci-on-pull_req.yml
- .github/workflows/ci-on-tags.yml
… and up `actions/cache` to `@v4`, see https://github.com/actions/cache#readme.
> [ci-on-pull_req.yml] Omit misleading "s" in comment

- translations/settings-patchmanager.ts
Specific command used on OpenSUSE:
`/usr/lib64/qt5/bin/lupdate src -ts translations/settings-patchmanager.ts`
> [translations/settings-patchmanager.ts] Update by runnning `lupdate`
